### PR TITLE
Add more playback speed steps

### PR DESCRIPTION
**Pull request by th0mcat**
I personally use and prefer 1.1x speed for audiobooks in other audiobook apps, figured other people might like some more granularity as well.

### CODE REVIEW

**Comment by mattttvaughn** [comment]
Not sure if you meant to close this out, but happy to merge this with maybe a few fewer options (too many and will go off the screen on most devices)

**Comment by th0mcat** [comment]
I closed it because I didn't have vector drawings for the additional options in `app/src/main/res/drawable/ic_speed_up_<new_speed>.xml`, which Android Studio kindly made me aware.  I've never done app development before and have all of < 3 months of python and C experience (so this could just be naivete), but I'm wondering if there's a way to print strings instead of having to store vector drawings for each.  If not, I'll try looking through some tutorials to see how to get `android:pathData=` for a vector drawing.  Any clue if those drawings use `lato.ttf` as the font?

**Comment by th0mcat** [comment]
Follow-up on:

> **I'm wondering if there's a way to print strings instead of having to store vector drawings for each.**

Here's an alternative implementation from the audiobook app Voice:

https://user-images.githubusercontent.com/37344783/160847040-448512ff-30b0-4a31-b9fe-f5a9969222e5.mp4

[Here's](https://github.com/PaulWoitaschek/Voice/search?q=playback+speed&type=commits) the commits for Voice for anything with "Playback Speed"

**Comment by lks-nbg** [comment]
I am working on something similar to what is shown in the video and can be seen in #7.
I may be able to finish my PR later that day and make it available for review & testing.

**Pull request closed without merging**
