### PR TITLE
Upgrades! Makes it work with android SDK version 33

### PR DESCRIPTION
**Pull request by dkowis**
Lots of updates
- Compile SDK version 33, Min SDK version 31.
- UPgrade to latest version of the android plugin for gradle.
- Include the 0.53 functionality (as I was told it made some things better, and why not?)
- Build with java 11, and target java 11
- Adjust the Compiler args for `opt-in`s
- Have to use `MASTER-snapshot` of the exoplayer codec extensions, or else have to build them ourselves.
- So many deprecation updates.
    - Latest Exoplayer was a big chunk of them, but updates to all the dependencies to bring it up to latest android SDK.
- kotlin version 1.8.10

Have verified by using on my local device, a Galaxy ZFold 4, and with a friend (tho he's still having playback problems, and we're not sure why)

Thought this might help others out there too that use it.

EDIT: updated what my local device is

### CODE REVIEW

**Comment by jblosser** [comment]
I am aforementioned friend and this PR does solve issues I was having on my s23 ultra; I had a pebkac issue that made me think it wasn't, but it was.

**Comment by dkowis** [comment]
I added another commit to solve a sleep timer crash related to insufficient permissions.

**Comment by mattttvaughn** [comment]
This is awesome stuff, thanks for doing some of the grunt work needed to make this stuff possible. It is working and running without issue on my device.

Everything in here looks good to me! I've pushed up some minor changes from my end:
 - Adding back skip silent audio (confirmed working on my device)
 - Removing that sensor permission since we won't need it for our use-case (confirmed still working on my device)
 - Some other minor build stuff

Feel to re-open this MR or open up an issue if anything changed causes you additional issues.

I've built an apk with all of this included, will add to releases

**Comment by mattttvaughn** [comment]
Build here: https://github.com/mattttvaughn/chronicle/releases/tag/0.54.0

**Pull request merged**
