### PR TITLE
Feature/collections

### PR DESCRIPTION
**Pull request by mattttvaughn**
MVP collections implementation

Not expecting anyone to do a full review of this PR- way too big and still a bit of an MVP!

But feel free to pull this down on your end and try things out. Use this PR to share/discuss if you run into any issues or have any suggestions

### CODE REVIEW

**Comment by mattttvaughn** [comment]
Closes #14

**Comment by lks-nbg** [comment]
Due to my limited android experience, I am not able to do a proper code review, but I have tried it and so far everything works as expected 👍

**Comment by dparamoshkin** [comment]
Much appreciated feature from my side, tried this branch on my phone, and it works great. Thanks a lot

**Comment by drtenant** [comment]
How to get this to work on Android chronicle

**Comment by dparamoshkin** [comment]
@mattttvaughn any plans to merge this PR?

**Pull request closed without merging**
